// <auto-generated />
using Ilm.CodeAudition.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ilm.CodeAudition.Service.Migrations
{
    [DbContext(typeof(TimesheetContext))]
    [Migration("20210708143610_ForeignKey")]
    partial class ForeignKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Ilm.CodeAudition.Service.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Ilm.CodeAudition.Service.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EmployeeId");

                    b.Property<int>("Friday");

                    b.Property<int>("Monday");

                    b.Property<string>("ProjectName");

                    b.Property<int>("Thursday");

                    b.Property<int>("Total");

                    b.Property<int>("Tuesday");

                    b.Property<int>("Wednesday");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("Ilm.CodeAudition.Service.Models.Timesheet", b =>
                {
                    b.HasOne("Ilm.CodeAudition.Service.Models.Employee", "Employee")
                        .WithMany("Timesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
